connect / as sysdba
CREATE USER emode_inc IDENTIFIED BY emode_inc;
GRANT connect, resource to emode_inc;
ALTER USER emode_inc QUOTA UNLIMITED ON USERS;

connect emode_inc/emode_inc;

CREATE TABLE ARTICLE_COLOR_LOOKUP (
    ARTICLE_CODE    NUMBER(6,0), 
    COLOR_CODE      NUMBER(4,0), 
    ARTICLE_LABEL   VARCHAR2(45), 
    COLOR_LABEL     VARCHAR2(30), 
    CATEGORY        VARCHAR2(25), 
    SALE_PRICE      NUMBER(13,2), 
    FAMILY_NAME     VARCHAR2(20), 
    FAMILY_CODE     VARCHAR2(3),
    OP_TYPE         CHAR(1),
    CONSTRAINT CHECK_OP_TYPE_ACL CHECK (OP_TYPE IN('i','u','d'))
);

CREATE TABLE ARTICLE_LOOKUP (
    ARTICLE_CODE    NUMBER(6,0), 
	ARTICLE_LABEL   VARCHAR2(45), 
	CATEGORY        VARCHAR2(25), 
	SALE_PRICE      NUMBER(13,2),
	FAMILY_NAME     VARCHAR2(20), 
	FAMILY_CODE     VARCHAR2(3),
	OP_TYPE         CHAR(1),
    CONSTRAINT CHECK_OP_TYPE_AL CHECK (OP_TYPE IN('i','u','d'))
);

CREATE TABLE CALENDAR_YEAR_LOOKUP (
	WEEK_KEY        NUMBER(3,0), 
	WEEK_IN_YEAR    NUMBER(2,0), 
	YEAR            NUMBER(4,0), 
	FISCAL_PERIOD   VARCHAR2(4), 
	YEAR_WEEK       VARCHAR2(7),
	QUARTER         NUMBER(1,0), 
	MONTH_NAME      VARCHAR2(10), 
	MONTH           NUMBER(2,0), 
	HOLIDAY_FLAG    VARCHAR2(1),
	OP_TYPE         CHAR(1),
    CONSTRAINT CHECK_OP_TYPE_CYL CHECK (OP_TYPE IN('i','u','d'))
);

CREATE TABLE OUTLET_LOOKUP (
	SHOP_CODE       NUMBER(3,0),	
	SHOP_NAME       VARCHAR2(30), 
	ADDRESS_1       VARCHAR2(20), 
	MANAGER         VARCHAR2(10), 
	DATE_OPEN       DATE, 
	OPEN            VARCHAR2(1), 
	OWNED_OUTRIGHT  VARCHAR2(1), 
	FLOOR_SPACE     NUMBER(4,0), 
	ZIP_CODE        VARCHAR2(6), 
	CITY            VARCHAR2(20), 
	STATE           VARCHAR2(20), 
	OP_TYPE         CHAR(1),
    CONSTRAINT CHECK_OP_TYPE_OL CHECK (OP_TYPE IN('i','u','d'))
);

CREATE TABLE SHOP_FACTS (
    ID              NUMBER(5,0) , 
    ARTICLE_CODE    NUMBER(6,0), 
    COLOR_CODE      NUMBER(4,0), 
    WEEK_KEY        NUMBER(3,0), 
    SHOP_CODE       NUMBER (3,0), 
    MARGIN          NUMBER(13,2), 
    AMOUNT_SOLD     NUMBER(13,2), 
    QUANTITY_SOLD   NUMBER(13,2),
	OP_TYPE         CHAR(1),
    CONSTRAINT CHECK_OP_TYPE_SF CHECK (OP_TYPE IN('i','u','d'))
);

GRANT INSERT, UPDATE, DELETE, SELECT
      ON ARTICLE_COLOR_LOOKUP
      TO emode;
	  
GRANT INSERT, UPDATE, DELETE, SELECT
      ON ARTICLE_LOOKUP
      TO emode;

GRANT INSERT, UPDATE, DELETE, SELECT
      ON OUTLET_LOOKUP
      TO emode;

GRANT INSERT, UPDATE, DELETE, SELECT
      ON CALENDAR_YEAR_LOOKUP
      TO emode;

GRANT INSERT, UPDATE, DELETE, SELECT
      ON SHOP_FACTS
      TO emode;