USE EMODE
GO

CREATE TABLE AUDIT_TRACE (	
	TRANSFER_NUM        int identity(1,1)   NOT NULL,
	TRANSFER_BEGIN_TIME datetime            NOT NULL,
	TRANSFER_END_TIME   datetime            NULL,
	CONSTRAINT PK_AUDIT_TRACE PRIMARY KEY (TRANSFER_NUM)
);
GO
CREATE TABLE AUDIT_INFO (
	INFO_NUM        int identity(1,1)   NOT NULL,
	TRANSFER_NUM    int                 NOT NULL,
    TABLE_NAME      varchar(20)         NOT NULL,
    ROWS_AFFECTED   int                 NOT NULL,
    OP_TYPE         char(1)             NOT NULL,
	CONSTRAINT PK_AUDIT_INFO PRIMARY KEY (INFO_NUM),
	CONSTRAINT FK_AUDIT_INFO_TRANSFER_NUM FOREIGN KEY (TRANSFER_NUM) REFERENCES AUDIT_TRACE(TRANSFER_NUM),
	CONSTRAINT CHECK_OP_TYPE_AI CHECK (OP_TYPE IN('i','d','u'))
);
GO
CREATE TABLE AUDIT_ERROR (
	ERROR_NUM       int identity(1,1)   NOT NULL,
	TRANSFER_NUM    int                 NOT NULL,
    TABLE_NAME      varchar(20)         NOT NULL,
    PK_VALUE        varchar(20)         NOT NULL,
    OP_TYPE         char(1)             NOT NULL,
    ERROR_CODE      varchar(25)         NOT NULL,
	CONSTRAINT PK_AUDIT_ERROR PRIMARY KEY (ERROR_NUM),
	CONSTRAINT FK_AUDIT_ERROR_TRANSFER_NUM FOREIGN KEY (TRANSFER_NUM) REFERENCES AUDIT_TRACE(TRANSFER_NUM),
	CONSTRAINT CHECK_OP_TYPE_AE CHECK (OP_TYPE IN('i','d','u'))
);

